-- V2: Seed news sources with reliability scores

INSERT INTO news_sources (domain, name, reliability_score, bias_rating, category, country) VALUES
('reuters.com', 'Reuters', 92, 'Center', 'WIRE_SERVICE', 'United Kingdom'),
('apnews.com', 'AP News', 90, 'Center', 'WIRE_SERVICE', 'United States'),
('bbc.co.uk', 'BBC News', 88, 'Center', 'MAINSTREAM', 'United Kingdom'),
('bbc.com', 'BBC News', 88, 'Center', 'MAINSTREAM', 'United Kingdom'),
('dw.com', 'Deutsche Welle', 85, 'Center', 'GOVERNMENT', 'Germany'),
('theguardian.com', 'The Guardian', 80, 'Left-Center', 'MAINSTREAM', 'United Kingdom'),
('nytimes.com', 'The New York Times', 82, 'Left-Center', 'MAINSTREAM', 'United States'),
('wsj.com', 'The Wall Street Journal', 82, 'Right-Center', 'MAINSTREAM', 'United States'),
('aljazeera.com', 'Al Jazeera', 78, 'Center', 'MAINSTREAM', 'Qatar'),
('ft.com', 'Financial Times', 84, 'Center', 'MAINSTREAM', 'United Kingdom'),
('economist.com', 'The Economist', 83, 'Center', 'MAINSTREAM', 'United Kingdom'),
('france24.com', 'France 24', 82, 'Center', 'GOVERNMENT', 'France'),
('rfi.fr', 'RFI', 80, 'Center', 'GOVERNMENT', 'France'),
('cnn.com', 'CNN', 74, 'Left-Center', 'MAINSTREAM', 'United States'),
('nbcnews.com', 'NBC News', 75, 'Left-Center', 'MAINSTREAM', 'United States'),
('washingtonpost.com', 'The Washington Post', 78, 'Left-Center', 'MAINSTREAM', 'United States'),
('foxnews.com', 'Fox News', 58, 'Right', 'MAINSTREAM', 'United States'),
('aa.com.tr', 'Anadolu Agency', 68, 'Right-Center', 'GOVERNMENT', 'Turkey'),
('rt.com', 'RT (Russia Today)', 28, 'Right', 'GOVERNMENT', 'Russia'),
('tass.com', 'TASS', 30, 'Right', 'GOVERNMENT', 'Russia'),
('xinhuanet.com', 'Xinhua', 32, 'Right', 'GOVERNMENT', 'China'),
('globaltimes.cn', 'Global Times', 28, 'Right', 'GOVERNMENT', 'China'),
('presstv.ir', 'Press TV', 25, 'Right', 'GOVERNMENT', 'Iran'),
('timesofisrael.com', 'Times of Israel', 70, 'Right-Center', 'MAINSTREAM', 'Israel'),
('haaretz.com', 'Haaretz', 76, 'Left-Center', 'MAINSTREAM', 'Israel'),
('dawn.com', 'Dawn', 72, 'Center', 'MAINSTREAM', 'Pakistan'),
('thehindu.com', 'The Hindu', 78, 'Left-Center', 'MAINSTREAM', 'India'),
('ndtv.com', 'NDTV', 70, 'Center', 'MAINSTREAM', 'India'),
('arabnews.com', 'Arab News', 62, 'Right-Center', 'MAINSTREAM', 'Saudi Arabia'),
('middleeasteye.net', 'Middle East Eye', 64, 'Left-Center', 'INDEPENDENT', 'United Kingdom'),
('reliefweb.int', 'ReliefWeb', 90, 'Center', 'INDEPENDENT', 'International'),
('un.org', 'United Nations', 85, 'Center', 'GOVERNMENT', 'International'),
('icrc.org', 'ICRC', 92, 'Center', 'INDEPENDENT', 'International'),
('hrw.org', 'Human Rights Watch', 82, 'Left-Center', 'INDEPENDENT', 'United States'),
('amnesty.org', 'Amnesty International', 80, 'Left-Center', 'INDEPENDENT', 'International');
